유지보수) system error - DevToolsActivePort file doesn't exist
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35

  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no
longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'orangepizero2w', ip: '127.0.1.1'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version:
'6.1.31-sun50iw9', java.version: '17.0.11'
Driver info: kr.andold.stock.crawler.ChromeDriverWrapper
Command: [null, newSession {capabilities=[Capabilities {browserName:
chrome, goog:chromeOptions: {args: [--remote-allow-origins=*,
--incognito, --enable-gpu, --verbose, --window-si
org.openqa.selenium.SessionNotCreatedException: Could not start a new
session. Response code 500. Message: session not created: Chrome failed
to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no
longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'orangepizero2w', ip: '127.0.1.1'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version:
'6.1.31-sun50iw9', java.version: '17.0.11'
Driver info: kr.andold.stock.crawler.ChromeDriverWrapper
Command: [null, newSession {capabilities=[Capabilities {browserName:
chrome, goog:chromeOptions: {args: [--remote-allow-origins=*,
--incognito, --enable-gpu, --verbose, --window-si