오류 및 방어 코드
실무에서는 네트워크 장비(방화벽, 프록시)나 일부 클라이언트 라이브러리가 GET 요청의 Body를 강제로 삭제해 버리는 일이
빈번합니다
2026-06-09 15:21:29 [ERROR] o.s.b.w.s.s.ErrorPageFilter      :182
Forwarding to error page from request [/api/crawl/item/ipo-close/recent]
due to exception [Cannot invoke
"java.time.ZonedDateTime.isBefore(java.time.chrono.ChronoZonedDateTime)"
because "this.start" is null]
java.lang.NullPointerException: Cannot invoke
"java.time.ZonedDateTime.isBefore(java.time.chrono.ChronoZonedDateTime)"
because "this.start" is null
        at kr.andold.stock.job.CrawlItemIpoCloseKindJob.containsOrModify(CrawlItemIpoCloseKindJob.java:74)