bug fix) exception
2026-04-30 17:50:39 [DEBUG] .CrawlItemDetailSeibroCompanyJob :128 ☎
┍ 종목종합내역::itemCompany(33166K)
2026-04-30 17:50:39 [ERROR] .CrawlItemDetailSeibroCompanyJob :225 ☎
┝ Exception:: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version:
'5.10.160-rockchip-rk356x', java.version: '21.0.7'
Driver info: kr.andold.utils.ChromeDriverWrapper
Command: [null, get
{url=https://seibro.or.kr/websquare/control.jsp?w2xPath=/IPORTAL/user/stock/BIP_CNTS02006V.xml&menuNo=44}]
Capabilities {acceptInsecureCerts: false, browserName: chrome,
browserVersion: 147.0.7727.116, chrome: {chromedriverVersion:
147.0.7727.116 (dbcf1b1bfb5..., userDataDir:
/home/andold/logs/stock/.se...}, fedcm:accounts: true,
goog:chromeOptions: {debuggerAddress: localhost:42381}, goog:processID:
3361779, networkConnectionEnabled: false, pageLoadStrategy: none,
platformName: linux, proxy: Proxy(), se:cdp:
ws://localhost:42381/devtoo..., se:cdpVersion: 147.0.7727.116,
setWindowRect: true, strictFileInteractability: false, timeouts:
{implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior:
dismiss and notify, webauthn:extension:credBlob: true,
webauthn:extension:largeBlob: true, webauthn:extension:minPinLength:
true, webauthn:extension:prf: true, webauthn:virtualAuthenticators:
true}
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using
WebDriver after calling quit()?
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version:
'5.10.160-rockchip-rk356x', java.version: '21.0.7'
Driver info: kr.andold.utils.ChromeDriverWrapper
Command: [null, get
{url=https://seibro.or.kr/websquare/control.jsp?w2xPath=/IPORTAL/user/stock/BIP_CNTS02006V.xml&menuNo=44}]
Capabilities {acceptInsecureCerts: false, browserName: chrome,
browserVersion: 147.0.7727.116, chrome: {chromedriverVersion:
147.0.7727.116 (dbcf1b1bfb5..., userDataDir:
/home/andold/logs/stock/.se...}, fedcm:accounts: true,
goog:chromeOptions: {debuggerAddress: localhost:42381}, goog:processID:
3361779, networkConnectionEnabled: false, pageLoadStrategy: none,
platformName: linux, proxy: Proxy(), se:cdp:
ws://localhost:42381/devtoo..., se:cdpVersion: 147.0.7727.116,
setWindowRect: true, strictFileInteractability: false, timeouts:
{implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior:
dismiss and notify, webauthn:extension:credBlob: true,
webauthn:extension:largeBlob: true, webauthn:extension:minPinLength:
true, webauthn:extension:prf: true, webauthn:virtualAuthenticators:
true}
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:304)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:1102)
        at kr.andold.stock.job.CrawlItemDetailSeibroCompanyJob.itemCompany(CrawlItemDetailSeibroCompanyJob.java:136)
        at kr.andold.stock.job.CrawlItemDetailSeibroCompanyJob.main(CrawlItemDetailSeibroCompanyJob.java:106)
        at kr.andold.stock.job.CrawlItemDetailSeibroCompanyJob.call(CrawlItemDetailSeibroCompanyJob.java:42)
        at kr.andold.stock.job.CrawlItemDetailSeibroCompanyJob.call(CrawlItemDetailSeibroCompanyJob.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2026-04-30 17:50:39 [WARN ] .CrawlItemDetailSeibroCompanyJob :229 ☎
┕ 『Result(status=EXCEPTION, result=null)』 종목종합내역::itemCompany(33166K) -
5 ms