bug fix) NPE
2026-04-29 23:16:15 [DEBUG] k.a.stock.job.CleanDividendJob   : 90 ◁
┍ cleanDividend(『462020 에이치엠씨제6호스팩 null』, 『#-1』)
2026-04-29 23:16:15 [ERROR] k.a.stock.service.JobService     :283 ♣
┝ run(kr.andold.stock.job.CleanDividendJob@1958bc8b) -
Exception::java.lang.NullPointerException: Cannot invoke
"java.util.List.iterator()" because "dividends" is null
java.util.concurrent.ExecutionException: java.lang.NullPointerException:
Cannot invoke "java.util.List.iterator()" because "dividends" is null