bug fix) start is null
[ERROR] awlDividendSeibroCompanyExcelJob :  89 ♀      ┝ Exception::
Cannot invoke "java.time.ZonedDateTime.format(java.time.format.DateTimeFormatter)"
because "this.start" is null
java.lang.NullPointerException: Cannot invoke
"java.time.ZonedDateTime.format(java.time.format.DateTimeFormatter)"
because "this.start" is null